const db = require('../config/db');

const findByEmail = async (email) => {
  const [rows] = await db.query('SELECT * FROM users WHERE email = ?', [email]);
  return rows[0] || null;
};

const findById = async (id) => {
  const [rows] = await db.query('SELECT * FROM users WHERE user_id = ?', [id]);
  return rows[0] || null;
};

const findAll = async () => {
  const [rows] = await db.query(
    'SELECT user_id, first_name, last_name, email, role, is_active, created_at FROM users'
  );
  return rows;
};

const findByRole = async (role) => {
  const [rows] = await db.query(
    'SELECT user_id, first_name, last_name, email, role, is_active, created_at FROM users WHERE role = ?',
    [role]
  );
  return rows;
};

// UUID is generated by MySQL's DEFAULT (UUID()), so we generate it here
// in JS first to be able to return/reference it immediately after insert.
const { randomUUID } = require('crypto');

const create = async ({ first_name, last_name, email, password_hash, role }) => {
  const user_id = randomUUID();
  await db.query(
    `INSERT INTO users (user_id, first_name, last_name, email, password_hash, role)
     VALUES (?, ?, ?, ?, ?, ?)`,
    [user_id, first_name, last_name, email, password_hash, role]
  );
  return { user_id, first_name, last_name, email, role };
};

const update = async (id, fields) => {
  const allowed = ['first_name', 'last_name', 'email', 'password_hash', 'role', 'is_active'];
  const keys = Object.keys(fields).filter((k) => allowed.includes(k) && fields[k] !== undefined);
  if (keys.length === 0) return null;

  const setClause = keys.map((k) => `${k} = ?`).join(', ');
  const values = keys.map((k) => fields[k]);

  const [result] = await db.query(
    `UPDATE users SET ${setClause} WHERE user_id = ?`,
    [...values, id]
  );
  return result.affectedRows > 0;
};

const deactivate = async (id) => {
  const [result] = await db.query(
    'UPDATE users SET is_active = FALSE WHERE user_id = ?',
    [id]
  );
  return result.affectedRows > 0;
};

module.exports = { findByEmail, findById, findAll, findByRole, create, update, deactivate };
